// Login event
export const CREATE_LOGIN_SUCCESS = 'CREATE_LOGIN_SUCCESS';
export const CREATE_LOGIN_ERROR = 'CREATE_LOGIN_ERROR';

export const GET_INITIAL_VALUE = 'GET_INITIAL_VALUE';

// Registration event
export const CREATE_REGITRATION_SUCCESS = 'CREATE_REGITRATION_SUCCESS';
export const CREATE_REGITRATION_ERROR = 'CREATE_REGITRATION_ERROR';

export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_ERROR = 'FORGET_PASSWORD_ERROR';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

// Otp code verification
export const OTP_VERIFICATION_SUCCESS = 'OTP_VERIFICATION_SUCCESS';
export const OTP_VERIFICATION_ERROR = 'OTP_VERIFICATION_ERROR';

// Resend Otp code verification
export const RESEND_OTP_VERIFICATION_SUCCESS =
  'RESEND_OTP_VERIFICATION_SUCCESS';
export const RESEND_OTP_VERIFICATION_ERROR = 'RESEND_OTP_VERIFICATION_ERROR';

// User-Profile
export const GET_USER_DETAILS = 'GET_USER_DETAILS';

// User Update
export const UPADTE_USER_DETAILS = 'UPADTE_USER_DETAILS';
export const UPADTE_USER_DETAILS_ERROR = 'UPADTE_USER_DETAILS_ERROR';

// Country data
export const GET_COUNTRY = 'GET_COUNTRY';

// State data
export const GET_STATE = 'GET_STATE';
export const GET_STATE_Error = 'GET_STATE_Error';

// City data
export const GET_CITY = 'GET_CITY';
export const GET_CITY_Error = 'GET_CITY_Error';

// Tech Status
export const GET_TECHNICIAN_STATUS = 'GET_TECHNICIAN_STATUS';
export const GET_TECHNICIAN_STATUS_ERROR = 'GET_TECHNICIAN_STATUS_ERROR';

// Previous Jobs
export const GET_PREVIOUS_JOBS = 'GET_PREVIOUS_JOBS';
export const GET_PREVIOUS_JOBS_ERROR = 'GET_PREVIOUS_JOBS_ERROR';

// Current Jobs
export const GET_CURRENT_JOBS = 'GET_CURRENT_JOBS';
export const GET_CURRENT_JOBS_ERROR = 'GET_CURRENT_JOBS_ERROR';

// Waiting Tickets
export const GET_WAITING_TICKETS = 'GET_WAITING_TICKETS';
export const GET_WAITING_TICKETS_ERROR = 'GET_WAITING_TICKETS_ERROR';

// User Data
export const GET_USER_DATA = 'GET_USER_DATA';

// Verify OTP
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR';

// CashBook
export const GET_CASH_BOOK = 'GET_CASH_BOOK';
export const GET_CASH_BOOK_ERROR = 'GET_CASH_BOOK_ERROR';

// Ticket Accept
export const ACCEPT_TICKET_SUCCESS = 'ACCEPT_TICKET_SUCCESS';
export const ACCEPT_TICKET_ERROR = 'ACCEPT_TICKET_ERROR';

// Ticket Refuse
export const REFUSE_TICKET_SUCCESS = 'REFUSE_TICKET_SUCCESS';
export const REFUSE_TICKET_ERROR = 'REFUSE_TICKET_ERROR';

// Ticket Complete
export const COMPLETE_TICKET_SUCCESS = 'COMPLETE_TICKET_SUCCESS';
export const COMPLETE_TICKET_ERROR = 'COMPLETE_TICKET_ERROR';

// Ticket Setting
export const TICKET_SETTING_SUCCESS = 'TICKET_SETTING_SUCCESS';
export const TICKET_SETTING_ERROR = 'TICKET_SETTING_ERROR';

export const GET_TICKET_DETAILS = 'GET_TICKET_DETAILS';
export const GET_TICKET_DETAILS_ERROR = 'GET_TICKET_DETAILS_ERROR';

// Report fields
export const GET_REPORT_FIELDS_SUCCESS = 'GET_REPORT_FIELDS_SUCCESS';
export const GET_REPORT_FIELDS_ERROR = 'GET_REPORT_FIELDS_ERROR';

// Report Submit
export const SUBMIT_REPORT_SUCCESS = 'SUBMIT_REPORT_SUCCESS';
export const SUBMIT_REPORT_ERROR = 'SUBMIT_REPORT_ERRO';

// Customer Name
export const GET_CUSTOMER_NAME_SUCCESS = 'GET_CUSTOMER_NAME_SUCCESS';
export const GET_CUSTOMER_NAME_ERROR = 'GET_CUSTOMER_NAME_ERROR';

// Request Cash
export const REQUEST_FOR_CASH_SUCCESS = 'REQUEST_FOR_CASH_SUCCESS';
export const REQUEST_FOR_CASH_ERROR = 'REQUEST_FOR_CASH_ERROR';

// Collect Cash
export const COLLECT_CASH_SUCCESS = 'COLLECT_CASH_SUCCESS';
export const COLLECT_CASH_ERROR = 'COLLECT_CASH_ERROR';

// Notes
export const CREATE_NEW_NOTES = 'CREATE_NEW_NOTES';
export const CREATE_NEW_NOTES_ERROR = 'CREATE_NEW_NOTES_ERROR';

// User Profile
export const UPLOAD_PROFILE_PIC = 'UPLOAD_PROFILE_PIC';
export const UPLOAD_PROFILE_PIC_ERROR = 'UPLOAD_PROFILE_PIC_ERROR';

export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_ERROR = 'DELETE_IMAGE_ERROR';
